name: duopet-ai
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  # Python version
  - python=3.10
  
  # Core dependencies
  - numpy=1.24.*
  - pandas=2.0.*
  - scipy=1.10.*
  
  # Deep Learning - PyTorch
  - pytorch=2.1.*
  - torchvision=0.16.*
  - torchaudio=2.1.*
  - pytorch-cuda=11.8  # GPU support
  
  # Deep Learning - TensorFlow (optional)
  - tensorflow=2.13.*
  - tensorflow-gpu=2.13.*
  
  # Computer Vision
  - opencv=4.8.*
  - pillow=10.0.*
  - scikit-image=0.21.*
  
  # Web Framework
  - fastapi=0.104.*
  - uvicorn=0.24.*
  - python-multipart=0.0.6
  
  # Database
  - cx_oracle=8.3.*
  - redis-py=5.0.*
  - sqlalchemy=2.0.*
  
  # ML/AI Tools
  - scikit-learn=1.3.*
  - transformers=4.35.*
  - langchain=0.0.340
  - openai=1.3.*
  
  # Development tools
  - jupyter=1.0.*
  - ipython=8.17.*
  - pytest=7.4.*
  - black=23.11.*
  - flake8=6.1.*
  
  # Other utilities
  - pydantic=2.5.*
  - python-dotenv=1.0.*
  - pyyaml=6.0.*
  - httpx=0.25.*
  - aiofiles=23.2.*
  
  # Pip dependencies (not available in conda)
  - pip
  - pip:
    - mediapipe==0.10.8
    - ultralytics==8.0.227
    - insightface==0.7.3
    - onnxruntime-gpu==1.16.3
    - deepface==0.0.79
    - face-recognition==1.3.0
    - dlib==19.24.2
    - streamlit==1.29.0
    - gradio==4.8.0
    - prometheus-client==0.19.0
    - python-jose[cryptography]==3.3.0
    - passlib[bcrypt]==1.7.4
    - emails==0.6
    - celery[redis]==5.3.4
    - flower==2.0.1
    - alembic==1.13.0
    - milvus-lite==2.3.3
    - chromadb==0.4.18
    - sentence-transformers==2.2.2
    - moviepy==1.0.3
    - pydub==0.25.1
    - soundfile==0.12.1
    - librosa==0.10.1
    - youtube-dl==2021.12.17
    - pytube==15.0.0
    - beautifulsoup4==4.12.2
    - selenium==4.15.2
    - scrapy==2.11.0
    - plotly==5.18.0
    - dash==2.14.1
    - tensorboard==2.15.1
    - wandb==0.16.1
    - mlflow==2.9.1