app:
  name: DuoPet AI Service
  version: 1.0.0
  description: AI Microservices for DuoPet Platform

server:
  host: ${API_HOST:0.0.0.0}
  port: ${API_PORT:8000}
  workers: ${API_WORKERS:4}
  debug: ${API_DEBUG:false}
  reload: false

models:
  base_path: ${MODEL_PATH:/app/db_models}
  
  face_recognition:
    model_name: deepface_vggface
    version: 1.0
    weights: face_recognition_v1.pth
    input_size: [224, 224]
    threshold: 0.85
    
  chatbot:
    keybert_model: paraphrase-multilingual-MiniLM-L12-v2
    gpt_model: gpt-4-turbo-preview
    max_tokens: 2000
    temperature: 0.7
    
  health_diagnosis:
    detection_model: yolov12_pet_disease_v1.pt
    classification_model: efficientnet_b4_pet_health_v1.pth
    num_classes: 15
    confidence_threshold: 0.7
    
  behavior_analysis:
    detection_model: yolov12_pet_detection_v1.pt
    pose_model: mediapipe_animal_pose_v1
    lstm_model: pet_behavior_lstm_v1.pth
    sequence_length: 30
    
  video_recommend:
    keybert_model: paraphrase-multilingual-MiniLM-L12-v2
    max_results: 20

preprocessing:
  image:
    max_size: 1920
    normalize_mean: [0.485, 0.456, 0.406]
    normalize_std: [0.229, 0.224, 0.225]
    
  video:
    fps: 30
    max_duration_seconds: 60
    chunk_size_seconds: 5

api:
  rate_limit:
    requests_per_minute: 60
    requests_per_hour: 1000
    
  response:
    timeout_seconds: 30
    max_payload_size_mb: 50
    
  authentication:
    enabled: true
    header_name: X-API-Key
    
monitoring:
  metrics:
    enabled: true
    endpoint: /metrics
    
  health_check:
    enabled: true
    endpoint: /health
    
  tracing:
    enabled: false
    service_name: duopet-ai
    
cache:
  redis:
    enabled: true
    ttl_seconds: 3600
    max_connections: 10
    
  local:
    enabled: true
    max_size_mb: 500

logging:
  level: ${LOG_LEVEL:INFO}
  format: json
  file:
    enabled: true
    path: ${LOG_FILE_PATH:/app/logs/duopet_ai.log}
    max_size: ${LOG_MAX_SIZE:100MB}
    backup_count: ${LOG_BACKUP_COUNT:5}
    
external_services:
  spring_boot:
    base_url: ${SPRING_BOOT_API_URL:http://localhost:8080/api}
    api_key: ${SPRING_BOOT_API_KEY}
    timeout: 30
    
  openai:
    api_key: ${OPENAI_API_KEY}
    organization: ${OPENAI_ORG_ID:}
    
  youtube:
    api_key: ${YOUTUBE_API_KEY}
    region_code: KR
    
features:
  face_login:
    enabled: true
    max_faces_per_user: 5
    
  chatbot:
    enabled: true
    context_memory_size: 10
    
  health_diagnosis:
    enabled: true
    supported_diseases:
      - skin_disease
      - eye_infection
      - ear_infection
      - dental_disease
      - obesity
      
  behavior_analysis:
    enabled: true
    behaviors:
      - walking
      - running
      - eating
      - sleeping
      - playing
      - aggressive
      - anxious
      
  video_recommend:
    enabled: true
    categories:
      - training
      - health
      - nutrition
      - grooming
      - entertainment